services:
  lunktrionapi:
    image: lunktrionapi:latest
    container_name: LunktrionAPI
    ports:
      - "50000:50000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=50000
      - ConnectionStrings__PostgreSQL=Host=postgresql;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672/
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
    build:
      context: ..
      dockerfile: LunktrionApi/LunktrionApi/Dockerfile
    depends_on:
      - postgresql
      - rabbitmq
      - redis
    networks:
      - lunktrionapi_network
  postgresql:
    image: postgres:16-alpine
    container_name: LunktrionAPI_PostgreSQL
    ports:
      - "50090:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Yekaterinburg
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - lunktrionapi_network
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: LunktrionAPI_RabbitMQ
    ports:
      - "50100:5672" 
      - "50110:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}
    networks:
      - lunktrionapi_network
  redis:
    image: redis:7-alpine
    container_name: LunktrionAPI_Redis
    ports:
      - "50101:6379"
    volumes:
      - redis_data:/data
    networks:
      - lunktrionapi_network
volumes:
  postgresql_data:
  rabbitmq_data:
  redis_data:
networks:
  lunktrionapi_network:
    driver: bridge