// <auto-generated />
using System;
using LunktrionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LunktrionApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LunktrionApi.Models.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DeviceManufacturer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_manufacturer");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceUUID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_uuid");

                    b.Property<string>("OperatingSystemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operating_system_name");

                    b.Property<string>("OperatingSystemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operating_system_type");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeviceUUID")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_device_uuid");

                    b.HasIndex("OperatingSystemType")
                        .HasDatabaseName("ix_devices_operating_system_type");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.DeviceCpuSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("NumberOfCores")
                        .HasColumnType("smallint")
                        .HasColumnName("number_of_cores");

                    b.Property<short>("NumberOfLogicalProcessors")
                        .HasColumnType("smallint")
                        .HasColumnName("number_of_logical_processors");

                    b.HasKey("Id")
                        .HasName("pk_device_cpu_specifications");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_cpu_specifications_device_id");

                    b.ToTable("device_cpu_specifications", (string)null);
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.DeviceDriveSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<long>("TotalSize")
                        .HasColumnType("bigint")
                        .HasColumnName("total_size");

                    b.HasKey("Id")
                        .HasName("pk_device_drive_specifications");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("is_device_drive_specifications_device_id");

                    b.ToTable("device_drive_specifications", (string)null);
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.DeviceGpuSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("VideoRam")
                        .HasColumnType("bigint")
                        .HasColumnName("video_ram");

                    b.HasKey("Id")
                        .HasName("pk_device_gpu_specifications");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_gpu_specifications_device_id");

                    b.ToTable("device_gpu_specifications", (string)null);
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.DeviceRamSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_device_ram_specifications");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("is_device_ram_specifications_device_id");

                    b.ToTable("device_ram_specifications", (string)null);
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.DeviceCpuSpecification", b =>
                {
                    b.HasOne("LunktrionApi.Models.Entities.Device", "Device")
                        .WithMany("CpuSpecifications")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_cpu_specifications_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.DeviceDriveSpecification", b =>
                {
                    b.HasOne("LunktrionApi.Models.Entities.Device", "Device")
                        .WithMany("DriveSpecifications")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_drive_specifications_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.DeviceGpuSpecification", b =>
                {
                    b.HasOne("LunktrionApi.Models.Entities.Device", "Device")
                        .WithMany("GpuSpecifications")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_gpu_specifications_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.DeviceRamSpecification", b =>
                {
                    b.HasOne("LunktrionApi.Models.Entities.Device", "Device")
                        .WithMany("RamSpecifications")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_ram_specifications_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LunktrionApi.Models.Entities.Device", b =>
                {
                    b.Navigation("CpuSpecifications");

                    b.Navigation("DriveSpecifications");

                    b.Navigation("GpuSpecifications");

                    b.Navigation("RamSpecifications");
                });
#pragma warning restore 612, 618
        }
    }
}
